[build]
  base = "peer"
  command = """
    npm run docs:build
  """
  publish = "/docs/.vitepress/dist"

[context.deploy-preview]
  command = """
    npm run docs:build
  """
  publish = "/docs/.vitepress/dist"

[build.environment]
  NODE_VERSION = "23.6.1"
