[build]
  base = "peer"  # 设置为 peer 目录
  command = """
    echo "Current Directory: $(pwd)"
    echo "Listing files:"
    ls -l
    npm install  # 安装依赖
    npm run docs:build  # 构建命令
  """
  publish = "peer/docs/.vitepress/dist"

[context.deploy-preview]
  command = """
    echo "Deploy Preview - Current Directory: $(pwd)"
    echo "Listing files:"
    ls -l
    npm install
    npm run docs:build
  """
  publish = "peer/docs/.vitepress/dist"

[build.environment]
  NODE_VERSION = "18.x"
