[build]
  base = "peer"
  command = """
    ls -l
    npm install
    npm run docs:build
  """
  publish = "/peer/docs/.vitepress/dist"

[context.deploy-preview]
  command = """
    ls -l
    npm install
    npm run docs:build
  """
  publish = "/peer/docs/.vitepress/dist"

[build.environment]
  NODE_VERSION = "18.x"
