[build]
  base = ""
  command = """
    echo "Current Directory: $(pwd)"
    echo "Listing files:"
    ls -l
    npm install
    npm run docs:build
  """
  publish = "/docs/.vitepress/dist"

[context.deploy-preview]
  command = """
    echo "Deploy Preview - Current Directory: $(pwd)"
    echo "Listing files:"
    ls -l
    npm install
    npm run docs:build
  """
  publish = "/docs/.vitepress/dist"

[build.environment]
  NODE_VERSION = "18.x"
